require: rubocop-rails

require: rubocop-rspec

AllCops:
 DisplayCopNames: true
 Exclude: 
   - db/**/*
   
RSpec/MultipleMemoizedHelpers:
 Enabled: false

RSpec/MultipleExpectations:
 Enabled: false
 
RSpec/PredicateMatcher:
 Enabled: false 

Metrics/LineLength:
 Max: 200

Style/FrozenStringLiteralComment:
 Enabled: false

Style/Documentation:
 Enabled: false

Metrics/MethodLength:
 Max: 12

Metrics/BlockLength:
 Enabled: false

Style/ClassAndModuleChildren:
 Enabled: false

Metrics/CyclomaticComplexity:
 Max: 9

Metrics/PerceivedComplexity:
 Max: 9

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/EmptyMethod:
  EnforcedStyle: expanded
  SupportedStyles:
    - compact
    - expanded
